-- MySQL Script generated by MySQL Workbench
-- Fri 12 Mar 2021 18:06:33 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jbj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jbj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jbj` ;
USE `jbj` ;

-- -----------------------------------------------------
-- Table `jbj`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbj`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `username`, `password`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jbj`.`radnici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbj`.`radnici` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `Kontakt_telefon` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_radnici_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_radnici_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `jbj`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_slovenian_ci;


-- -----------------------------------------------------
-- Table `jbj`.`evidencija_sati`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jbj`.`evidencija_sati` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prijava` TIME NOT NULL,
  `odjava` TIME NOT NULL,
  `datum` DATE NOT NULL,
  `ukupno_sati` TIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_evidencija_sati_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_evidencija_sati_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `jbj`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
